config/routes.rb
Rails.application.routes.draw do

  resources :people
  root :to => "people#index"
  mount Resque::Server, :at => "/resque"  
end

app/models/person.rb
class Person < ActiveRecord::Base
	require 'date'

	validates :first_name , presence: true, length: { maximum: 75 }
	validates :last_name , presence: true, length: { maximum: 75 }
	validates :email, presence: true, length: { maximum: 254 }, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "Enter a valid Email" , on: :create }	
	validates :job , length: { maximum: 75 }
	validates :bio , length: { minimum: 30 }
	validates :gender, :inclusion => { :in => %w( male female ), :message => "Please select a gender" }
	validates :birthdate, presence: true#, :is_valid_date
	
	def name
	 first_name + " "+ last_name	
	end

	def age
		now = Time.now.utc.to_date
		age = now.year - birthdate.year - (birthdate.to_date.change(:year => now.year) > now ? 1 : 0)
		age
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
  	@people = Person.all.order(:first_name, :last_name)
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      Resque.enqueue(PersonMailerCreatedQueue,@person.id)
      redirect_to @person, notice: 'Person was successfully created.'
    else
      render :new 
    end
  end

  def new
  	@person = Person.new
  end

  def edit
    @person.birthdate =  @person.birthdate.strftime("%d/%m/%Y")
  end

  def show
  end

  def update
     if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
     else
      render :edit
     end
  end

  def destroy
    if @person.destroy
      Resque.enqueue(PersonMailerDeletedQueue,{ "name" => @person.name, "email" => @person.email })
      redirect_to people_path, notice: 'Person deleted.'
    else
      redirect_to people_path, notice: 'Person could not be deleted.'
    end
  end

  private
    def set_person
      @person = Person.find(params[:id])
    end

    def person_params
      params.require(:person).permit(:first_name,:last_name,:email,:job,:bio,:gender,:birthdate,:picture)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.slim
doctype html
html
 head
  title ThruU
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags 
 =yield 

app/views/people/_partial.html.slim
p#notice =notice

= form_for(@person) do |f| 
 .row
 .col-md-6
  .field
   = f.text_field  :first_name,	:class => "form-control", :placeholder => "First Name"
   = f.text_field  :last_name,	:class => "form-control", :placeholder => "Last Name"
   = f.text_field  :email,		  :class => "form-control", :placeholder => "Email"
   = f.text_field  :job,			  :class => "form-control", :placeholder => "Job"
   = f.text_area   :bio,			  :class => "form-control", :placeholder => "Biography", rows: 6
   = f.select      :gender, options_for_select([["Select Gender", ""],['Female', 'female'], ['Male', 'male']],:selected => @person.gender),{},:class => "form-control"
   = f.text_field  :birthdate,	:class => "datepicker form-control", "data-provide" => 'datepicker', :placeholder => "Birthdate", "data-date-end-date" => "0d", "data-date-format" => "dd/mm/yyyy"
   
  .actions
   =f.submit nil, :class => "btn btn-default"
   = link_to ' Back', people_path
 .col-md-6
  -if @person.errors.any?
   #error_explanation
    h4 =pluralize(@person.errors.count, "error")
    ul.list-group
     -@person.errors.full_messages.each do |message|
      li.list-group-item =message

app/views/people/edit.html.slim
.container
 div style="display: -webkit-box;"
   h2 Editing Person
   =link_to @person do
     span.glyphicon.glyphicon-remove style="padding-top: 33px;padding-left: 4px" title="Cancel"
 br
 = render 'partial'

app/views/people/index.html.slim
p#notice =notice

.container
 
 .list-page 
  .space
  .space
  div style="display: -webkit-box;"
   h1 Persons
   =link_to new_person_path do
     span.glyphicon.glyphicon-plus style="padding-top: 37px;padding-left: 4px" title="Add Person"
 -if !@people.empty? 
  table.table.tablesorter
    thead
     tr
      th width="40%" First name & Last name 
      th width="20%" Email
      th width="15%" Age
      th width="15%" Action
    tbody
     -@people.each do |person|
      tr


       td= link_to person.name, person
       td= person.email
       td= person.age
       td= link_to person, method: :delete, data: { confirm: 'Are you sure?' } do
            span.glyphicon.glyphicon-trash title="Delete"
 -else
  p No people to show

app/views/people/new.html.slim
.container 
 h2 Create Person
 br
 = render 'partial'

app/views/people/show.html.slim
.container 
 p#notice =notice
 
 .space
	.row.profile
		.col-md-4
			=image_tag(@person.picture, class: "img-circle", size: "300x300")
			
		.col-md-6 
		 div style="display: -webkit-box;"
		  h1 = @person.first_name.concat(" ").concat(@person.last_name)
		  =link_to edit_person_path(@person) do
		   span.glyphicon.glyphicon-pencil style="padding-top: 37px;" title="Edit"
		  =link_to people_path do
		   span.glyphicon.glyphicon-remove style="padding-top: 37px;" title="Cancel"
		  =link_to @person, method: :delete, data: { confirm: 'Are you sure?' } do
		   span.glyphicon.glyphicon-trash style="padding-top: 37px;" title="Delete"
		 - @person.job = @person.job.presence || 'No Job'
		 table.table
		  tr
		   td Job
		   td= @person.job
		  tr
		   td Email
		   td= @person.email
		  tr
		   td Birthdate
		   td= @person.birthdate
		  tr
		   td Gender
		   td= @person.gender.capitalize   
		  tr
		   td Picture
		   td= @person.picture 
	.row.biography
	 h2 Biography
	 p = @person.bio